
/* Drop Tables */

DROP TABLE ADMIN_TAB CASCADE CONSTRAINTS;
DROP TABLE BUY_COUPON CASCADE CONSTRAINTS;
DROP TABLE CR_JOIN CASCADE CONSTRAINTS;
DROP TABLE DELADDR CASCADE CONSTRAINTS;
DROP TABLE USE_SAILCUPPON CASCADE CONSTRAINTS;
DROP TABLE MY_CUPON CASCADE CONSTRAINTS;
DROP TABLE S_TOPPING CASCADE CONSTRAINTS;
DROP TABLE SALES_MENU CASCADE CONSTRAINTS;
DROP TABLE WHETHER CASCADE CONSTRAINTS;
DROP TABLE SALES CASCADE CONSTRAINTS;
DROP TABLE USE_GIFT CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE GIFT_DATE CASCADE CONSTRAINTS;
DROP TABLE GIFTCONE_C CASCADE CONSTRAINTS;
DROP TABLE GIFTCONE CASCADE CONSTRAINTS;
DROP TABLE P_NUTRIENT CASCADE CONSTRAINTS;
DROP TABLE PIZZA_DOUGH CASCADE CONSTRAINTS;
DROP TABLE DOUGH CASCADE CONSTRAINTS;
DROP TABLE DRINK CASCADE CONSTRAINTS;
DROP TABLE Event CASCADE CONSTRAINTS;
DROP TABLE IMGSRC CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE PICKLE CASCADE CONSTRAINTS;
DROP TABLE PIZZA CASCADE CONSTRAINTS;
DROP TABLE PIZZA_SAUCE CASCADE CONSTRAINTS;
DROP TABLE RATING_CUPPON CASCADE CONSTRAINTS;
DROP TABLE RATING CASCADE CONSTRAINTS;
DROP TABLE SAILE_COUPON CASCADE CONSTRAINTS;
DROP TABLE SAUCE CASCADE CONSTRAINTS;
DROP TABLE S_NUTRIENT CASCADE CONSTRAINTS;
DROP TABLE SIDE CASCADE CONSTRAINTS;
DROP TABLE STORES CASCADE CONSTRAINTS;
DROP TABLE TOPPING_SIZE CASCADE CONSTRAINTS;
DROP TABLE T_NUTRIENT CASCADE CONSTRAINTS;
DROP TABLE TOPPING CASCADE CONSTRAINTS;




DROP SEQUENCE SEQ_PIZZA_P_NO;
DROP SEQUENCE SEQ_DOUGH_DOUGH_NO;
DROP SEQUence SEQ_PIZZA_DOUGH_D_NO;
DROP SEQUENCE SEQ_P_NUTRIENT_N_NO;
DROP SEQUENCE SEQ_SIDE_S_NO;
DROP SEQUENCE  SEQ_SALES_SA_NO;
DROP SEQUENCE  SEQ_STORES_ST_NO;
DROP SEQUENCE SEQ_TOPPING_SIZE_TS_NO;
DROP SEQUENCE SEQ_TOPPING_T_CODE;
DROP SEQUENCE  SEQ_SAUCE_SC_NO;
DROP SEQUENCE SEQ_PICKLE_PC_NO;
DROP SEQUENCE SEQ_DRINK_DR_NO;
DROP SEQUENCE SEQ_RATING_R_NO;
DROP SEQUENCE SEQ_RATING_CUPPON_RC_NO;
DROP SEQUENCE  SEQ_EVENT_E_NO;
DROP SEQUENCE  SEQ_NOTICE_N_NO;
DROP SEQUENCE  SEQ_SAILE_COUPON_C_NO;
DROP SEQUENCE  SEQ_MC_COUPON_MC_NO;
DROP SEQUENCE SEQ_SALES_MENU_SM_NO;
DROP SEQUENCE SEQ_DELADDR_DE_NO;
DROP SEQUENCE SEQ_PIZZA_SAUCE_PS_NO;

CREATE SEQUENCE SEQ_PIZZA_SAUCE_PS_NO START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DOUGH_DOUGH_NO START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
create sequence SEQ_PIZZA_DOUGH_D_NO START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_P_NUTRIENT_N_NO START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SIDE_S_NO    START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PIZZA_P_NO START WITH 1 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SALES_SA_NO   START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_STORES_ST_NO   START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TOPPING_SIZE_TS_NO START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TOPPING_T_CODE START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SAUCE_SC_NO   START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PICKLE_PC_NO    START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DRINK_DR_NO  START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_RATING_R_NO    START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_RATING_CUPPON_RC_NO    START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EVENT_E_NO   START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NOTICE_N_NO   START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SAILE_COUPON_C_NO   START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MC_COUPON_MC_NO   START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SALES_MENU_SM_NO START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DELADDR_DE_NO  START WITH 0 MINVALUE -99  NOCACHE NOCYCLE;


PURGE RECYCLEBIN;




/* Create Tables */

CREATE TABLE ADMIN_TAB
(
	Ad_ID nvarchar2(15) NOT NULL,
	AD_PASS nvarchar2(15),
	PRIMARY KEY (Ad_ID)
);


CREATE TABLE BUY_COUPON
(
	-- xxxxxx-xxxxxx 형식으로 저장
	G_CODE nvarchar2(13) NOT NULL,
	ID nvarchar2(15) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE CR_JOIN
(
	ID nvarchar2(15) NOT NULL,
	R_NO number NOT NULL,
	-- 역정규화
	R_NAME nvarchar2(20)
);


CREATE TABLE CUSTOMER
(
	ID nvarchar2(15) NOT NULL,
	PASS nvarchar2(15) NOT NULL,
	NAME nvarchar2(20) NOT NULL,
	-- M- 남자
	-- W- 여자
	GENDER char(1) NOT NULL,
	BIRTH nvarchar2(8),
	POST nvarchar2(20) NOT NULL,
	ADDR nvarchar2(200) NOT NULL,
	-- 
	-- 
	EMAIL nvarchar2(50) NOT NULL,
	TEL nvarchar2(13) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE DELADDR
(
	DE_NO number NOT NULL,
	ID nvarchar2(15) NOT NULL,
	ST_NO number NOT NULL,
	DE_ADDR nvarchar2(50),
	DE_KIND nvarchar2(5),
	PRIMARY KEY (DE_NO)
);


CREATE TABLE DOUGH
(
	DOUGH_NO number NOT NULL,
	DOUGH_NAME nvarchar2(20) NOT NULL,
	D_PRICE number,
	PRIMARY KEY (DOUGH_NO)
);


CREATE TABLE DRINK
(
	DR_NO number NOT NULL,
	D_NAME nvarchar2(50),
	D_PRICE number,
	D_IMG nvarchar2(50),
	PRIMARY KEY (DR_NO)
);


CREATE TABLE Event
(
	E_NO number NOT NULL,
	E_TITLE nvarchar2(200),
	E_SDATE date DEFAULT SYSDATE,
	E_EDATE date DEFAULT SYSDATE,
	E_TIMG nvarchar2(50),
	E_CIMG nvarchar2(50),
	PRIMARY KEY (E_NO)
);


CREATE TABLE GIFTCONE
(
	COUPON_NO number NOT NULL,
	D_NO number NOT NULL,
	C_SIZE nvarchar2(3),
	PRIMARY KEY (COUPON_NO)
);


CREATE TABLE GIFTCONE_C
(
	-- xxxxxx-xxxxxx 형식으로 저장
	G_CODE nvarchar2(13) NOT NULL,
	COUPON_NO number NOT NULL,
	PRIMARY KEY (G_CODE)
);


CREATE TABLE GIFT_DATE
(
	-- xxxxxx-xxxxxx 형식으로 저장
	G_CODE nvarchar2(13) NOT NULL,
	GD_SDATE date DEFAULT SYSDATE,
	GD_EDATE date
);


CREATE TABLE IMGSRC
(
	SRC nvarchar2(300)
);


CREATE TABLE MY_CUPON
(
	MC_NO number NOT NULL,
	ID nvarchar2(15) NOT NULL,
	C_SDATE date,
	C_EDATE date,
	C_NO number NOT NULL,
	PRIMARY KEY (MC_NO)
);


CREATE TABLE NOTICE
(
	N_NO number NOT NULL,
	N_TITLE nvarchar2(200),
	N_CONTENT nvarchar2(2000),
	N_DATE date DEFAULT SYSDATE,
	N_IMG nvarchar2(50),
	-- 1=공지
	-- 2=PRESS
	N_TYPE number,
	N_COUNT number,
	PRIMARY KEY (N_NO)
);


CREATE TABLE PICKLE
(
	PC_NO number NOT NULL,
	PC_NAME nvarchar2(50),
	PC_PRICE number,
	PC_IMG nvarchar2(50),
	PRIMARY KEY (PC_NO)
);


CREATE TABLE PIZZA
(
	P_NO number NOT NULL,
	-- 피자 이
	P_NAME nvarchar2(50),
	P_KIND nvarchar2(10),
	-- 상세정보 - 토핑 클릭시 나오는 문자열들
	-- 
	--  
	P_TOPPING nvarchar2(500),
	P_SPRICE number,
	P_LPRICE number,
	-- 상세정보_원산지
	-- 
	P_ORIGIN nvarchar2(500),
	-- 피자 이미지파일
	P_IMG nvarchar2(50),
	-- 피자 이미지파일
	P_HIMG nvarchar2(50),
	P_DIMG nvarchar2(50),
	P_DETAIL nvarchar2(500),
	PRIMARY KEY (P_NO)
);


CREATE TABLE PIZZA_DOUGH
(
	D_NO number NOT NULL,
	P_NO number NOT NULL,
	DOUGH_NO number NOT NULL,
	PRIMARY KEY (D_NO)
);


CREATE TABLE PIZZA_SAUCE
(
	PS_NO number NOT NULL,
	PS_NAME nvarchar2(15),
	PRIMARY KEY (PS_NO)
);


CREATE TABLE P_NUTRIENT
(
	N_NO number NOT NULL,
	D_NO number,
	N_SIZE nvarchar2(10),
	N_GRAM number,
	N_STAN nvarchar2(10),
	N_STANGRAM number,
	N_KCAL number,
	N_PROTEIN number,
	N_SFAT number,
	N_NATRIUM number,
	N_SUGAR number,
	PRIMARY KEY (N_NO)
);


CREATE TABLE RATING
(
	R_NO number NOT NULL,
	R_NAME nvarchar2(20),
	-- X회 구매시 
	R_TARGET number,
	R_IMG nvarchar2(50),
	PRIMARY KEY (R_NO)
);


CREATE TABLE RATING_CUPPON
(
	RC_NO number NOT NULL,
	R_NO number NOT NULL,
	C_NO number NOT NULL,
	PRIMARY KEY (RC_NO)
);


CREATE TABLE SAILE_COUPON
(
	C_NO number NOT NULL,
	C_NAME nvarchar2(50) NOT NULL,
	--  % 혹은 액수
	C_SAILE number,
	-- 0 = 모두
	-- 1 = 배달
	-- 2 = 포장
	-- 3 = 생일
	C_CON number,
	PRIMARY KEY (C_NO)
);


CREATE TABLE SALES
(
	SA_NO number NOT NULL,
	ID nvarchar2(15) NOT NULL,
	ST_NO number NOT NULL,
	SA_ADDR nvarchar2(100),
	-- 시간까지!!!
	-- 
	SA_DATE date DEFAULT SYSDATE,
	SA_PRO nvarchar2(15) DEFAULT '주문 상태 - 미승인',
	PRIMARY KEY (SA_NO)
);


CREATE TABLE SALES_MENU
(
	SM_NO number NOT NULL,
	SA_NO number NOT NULL,
	MENU_NO number,
	-- 1 = 피자
	-- 2 = 사이드메뉴
	-- 3 = 음료수
	-- 4 = 피클
	-- 5 = 소스
	MENU_KIND number,
	-- 편의를 위한 역정규화
	MENU_NAME nvarchar2(20),
	MENU_QTY number,
	MENU_SIZE nvarchar2(1),
	MENU_PRICE number,
	PRIMARY KEY (SM_NO)
);


CREATE TABLE SAUCE
(
	SC_NO number NOT NULL,
	SC_NAME nvarchar2(50),
	SC_PRICE number,
	SC_IMG nvarchar2(50),
	PRIMARY KEY (SC_NO)
);


CREATE TABLE SIDE
(
	S_NO number NOT NULL,
	S_NAME nvarchar2(50) NOT NULL,
	S_PRICE number,
	S_IMG nvarchar2(50),
	S_ORIGIN nvarchar2(500),
	S_DETAIL nvarchar2(500),
	PRIMARY KEY (S_NO)
);


CREATE TABLE STORES
(
	ST_NO number NOT NULL,
	ST_NAME nvarchar2(50) NOT NULL,
	ST_ID nvarchar2(15) NOT NULL,
	ST_PASS nvarchar2(15),
	ST_TEL nvarchar2(13),
	ST_POST nvarchar2(12),
	-- 매장 주소 안내시 출력될주소
	-- 
	ST_ADDR nvarchar2(70),
	ST_PARKIN nvarchar2(50),
	ST_TIME nvarchar2(15),
	-- 1 = 10KM 쯤 되는듯
	ST_XPOS number,
	-- 1=10KM?
	ST_YPOS number,
	PRIMARY KEY (ST_NO)
);


CREATE TABLE S_NUTRIENT
(
	S_NO number NOT NULL,
	S_GRAM number,
	S_KCAL number,
	S_PROTEIN number,
	S_SFAT number,
	S_NATRIUM number,
	S_SUGAR number
);


CREATE TABLE S_TOPPING
(
	SM_NO number NOT NULL,
	TS_NO number NOT NULL
);


CREATE TABLE TOPPING
(
	-- 뷰 에서 ID 값으로 사용
	T_CODE nvarchar2(20) NOT NULL,
	T_NAME nvarchar2(20),
	-- 토핑 이미지
	T_IMG nvarchar2(30),
	-- 분류
	-- 
	T_KIND nvarchar2(15),
	T_ALLERGY nvarchar2(60),
	PRIMARY KEY (T_CODE)
);


CREATE TABLE TOPPING_SIZE
(
	TS_NO number NOT NULL,
	-- 뷰 에서 ID 값으로 사용
	T_CODE nvarchar2(20) NOT NULL,
	T_SIZE char(1),
	T_PRICE number,
	T_GRAM nvarchar2(15),
	PRIMARY KEY (TS_NO)
);


CREATE TABLE T_NUTRIENT
(
	-- 뷰 에서 ID 값으로 사용
	T_CODE nvarchar2(20) NOT NULL,
	T_KCAL nvarchar2(20),
	T_PROTEIN nvarchar2(20),
	T_SFAT nvarchar2(20),
	T_NATRIUM nvarchar2(20),
	T_SUGAR nvarchar2(20)
);


CREATE TABLE USE_GIFT
(
	-- xxxxxx-xxxxxx 형식으로 저장
	G_CODE nvarchar2(13) NOT NULL,
	-- 사용한 고객
	ID nvarchar2(15) NOT NULL,
	ST_NO number NOT NULL,
	USE_DATE date DEFAULT SYSDATE
);


CREATE TABLE USE_SAILCUPPON
(
	MC_NO number NOT NULL,
	US_DATE date DEFAULT SYSDATE
);


CREATE TABLE WHETHER
(
	SA_NO number NOT NULL,
	W_PRO nvarchar2(12)
);



/* Create Foreign Keys */

ALTER TABLE BUY_COUPON
	ADD FOREIGN KEY (ID)
	REFERENCES CUSTOMER (ID) ON DELETE CASCADE
;


ALTER TABLE CR_JOIN
	ADD FOREIGN KEY (ID)
	REFERENCES CUSTOMER (ID) ON DELETE CASCADE
;


ALTER TABLE DELADDR
	ADD FOREIGN KEY (ID)
	REFERENCES CUSTOMER (ID) ON DELETE CASCADE
;


ALTER TABLE MY_CUPON
	ADD FOREIGN KEY (ID)
	REFERENCES CUSTOMER (ID) ON DELETE CASCADE
;


ALTER TABLE SALES
	ADD FOREIGN KEY (ID)
	REFERENCES CUSTOMER (ID) ON DELETE CASCADE
;


ALTER TABLE USE_GIFT
	ADD FOREIGN KEY (ID)
	REFERENCES CUSTOMER (ID) ON DELETE CASCADE
;


ALTER TABLE PIZZA_DOUGH
	ADD FOREIGN KEY (DOUGH_NO)
	REFERENCES DOUGH (DOUGH_NO) ON DELETE CASCADE
;


ALTER TABLE GIFTCONE_C
	ADD FOREIGN KEY (COUPON_NO)
	REFERENCES GIFTCONE (COUPON_NO) ON DELETE CASCADE
;


ALTER TABLE BUY_COUPON
	ADD FOREIGN KEY (G_CODE)
	REFERENCES GIFTCONE_C (G_CODE) ON DELETE CASCADE
;


ALTER TABLE GIFT_DATE
	ADD FOREIGN KEY (G_CODE)
	REFERENCES GIFTCONE_C (G_CODE) ON DELETE CASCADE
;


ALTER TABLE USE_GIFT
	ADD FOREIGN KEY (G_CODE)
	REFERENCES GIFTCONE_C (G_CODE) ON DELETE CASCADE
;


ALTER TABLE USE_SAILCUPPON
	ADD FOREIGN KEY (MC_NO)
	REFERENCES MY_CUPON (MC_NO) ON DELETE CASCADE
;


ALTER TABLE PIZZA_DOUGH
	ADD FOREIGN KEY (P_NO)
	REFERENCES PIZZA (P_NO) ON DELETE CASCADE
;


ALTER TABLE GIFTCONE
	ADD FOREIGN KEY (D_NO)
	REFERENCES PIZZA_DOUGH (D_NO) ON DELETE CASCADE
;


ALTER TABLE P_NUTRIENT
	ADD FOREIGN KEY (D_NO)
	REFERENCES PIZZA_DOUGH (D_NO) ON DELETE CASCADE
;


ALTER TABLE CR_JOIN
	ADD FOREIGN KEY (R_NO)
	REFERENCES RATING (R_NO) ON DELETE CASCADE
;


ALTER TABLE RATING_CUPPON
	ADD FOREIGN KEY (R_NO)
	REFERENCES RATING (R_NO) ON DELETE CASCADE
;


ALTER TABLE MY_CUPON
	ADD FOREIGN KEY (C_NO)
	REFERENCES SAILE_COUPON (C_NO) ON DELETE CASCADE
;


ALTER TABLE RATING_CUPPON
	ADD FOREIGN KEY (C_NO)
	REFERENCES SAILE_COUPON (C_NO) ON DELETE CASCADE
;


ALTER TABLE SALES_MENU
	ADD FOREIGN KEY (SA_NO)
	REFERENCES SALES (SA_NO) ON DELETE CASCADE
;


ALTER TABLE WHETHER
	ADD FOREIGN KEY (SA_NO)
	REFERENCES SALES (SA_NO) ON DELETE CASCADE
;


ALTER TABLE S_TOPPING
	ADD FOREIGN KEY (SM_NO)
	REFERENCES SALES_MENU (SM_NO) ON DELETE CASCADE
;


ALTER TABLE S_NUTRIENT
	ADD FOREIGN KEY (S_NO)
	REFERENCES SIDE (S_NO) ON DELETE CASCADE
;


ALTER TABLE DELADDR
	ADD FOREIGN KEY (ST_NO)
	REFERENCES STORES (ST_NO) ON DELETE CASCADE
;


ALTER TABLE SALES
	ADD FOREIGN KEY (ST_NO)
	REFERENCES STORES (ST_NO) ON DELETE CASCADE
;


ALTER TABLE USE_GIFT
	ADD FOREIGN KEY (ST_NO)
	REFERENCES STORES (ST_NO) ON DELETE CASCADE
;


ALTER TABLE TOPPING_SIZE
	ADD FOREIGN KEY (T_CODE)
	REFERENCES TOPPING (T_CODE) ON DELETE CASCADE
;


ALTER TABLE T_NUTRIENT
	ADD FOREIGN KEY (T_CODE)
	REFERENCES TOPPING (T_CODE) ON DELETE CASCADE
;


ALTER TABLE S_TOPPING
	ADD FOREIGN KEY (TS_NO)
	REFERENCES TOPPING_SIZE (TS_NO) ON DELETE CASCADE
;



/* Comments */

COMMENT ON COLUMN BUY_COUPON.G_CODE IS 'xxxxxx-xxxxxx 형식으로 저장';
COMMENT ON COLUMN CR_JOIN.R_NAME IS '역정규화';
COMMENT ON COLUMN CUSTOMER.GENDER IS 'M- 남자
W- 여자';
COMMENT ON COLUMN CUSTOMER.EMAIL IS '
';
COMMENT ON COLUMN GIFTCONE_C.G_CODE IS 'xxxxxx-xxxxxx 형식으로 저장';
COMMENT ON COLUMN GIFT_DATE.G_CODE IS 'xxxxxx-xxxxxx 형식으로 저장';
COMMENT ON COLUMN NOTICE.N_TYPE IS '1=공지
2=PRESS';
COMMENT ON COLUMN PIZZA.P_NAME IS '피자 이';
COMMENT ON COLUMN PIZZA.P_TOPPING IS '상세정보 - 토핑 클릭시 나오는 문자열들

 ';
COMMENT ON COLUMN PIZZA.P_ORIGIN IS '상세정보_원산지
';
COMMENT ON COLUMN PIZZA.P_IMG IS '피자 이미지파일';
COMMENT ON COLUMN PIZZA.P_HIMG IS '피자 이미지파일';
COMMENT ON COLUMN RATING.R_TARGET IS 'X회 구매시 ';
COMMENT ON COLUMN SAILE_COUPON.C_SAILE IS ' % 혹은 액수';
COMMENT ON COLUMN SAILE_COUPON.C_CON IS '0 = 모두
1 = 배달
2 = 포장
3 = 생일';
COMMENT ON COLUMN SALES.SA_DATE IS '시간까지!!!
';
COMMENT ON COLUMN SALES_MENU.MENU_KIND IS '1 = 피자
2 = 사이드메뉴
3 = 음료수
4 = 피클
5 = 소스';
COMMENT ON COLUMN SALES_MENU.MENU_NAME IS '편의를 위한 역정규화';
COMMENT ON COLUMN STORES.ST_ADDR IS '매장 주소 안내시 출력될주소
';
COMMENT ON COLUMN STORES.ST_XPOS IS '1 = 10KM 쯤 되는듯';
COMMENT ON COLUMN STORES.ST_YPOS IS '1=10KM?';
COMMENT ON COLUMN TOPPING.T_CODE IS '뷰 에서 ID 값으로 사용';
COMMENT ON COLUMN TOPPING.T_IMG IS '토핑 이미지';
COMMENT ON COLUMN TOPPING.T_KIND IS '분류
';
COMMENT ON COLUMN TOPPING_SIZE.T_CODE IS '뷰 에서 ID 값으로 사용';
COMMENT ON COLUMN T_NUTRIENT.T_CODE IS '뷰 에서 ID 값으로 사용';
COMMENT ON COLUMN USE_GIFT.G_CODE IS 'xxxxxx-xxxxxx 형식으로 저장';
COMMENT ON COLUMN USE_GIFT.ID IS '사용한 고객';



